version: '3.8'

services:
  resume-chat:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./parsed:/app/parsed
    restart: unless-stopped
